### ISSUE TITLE
Two Finger Touch Required to Select School from Search Window

### ISSUE THREAD

**Issue by JMichaelScott** [PlutoNetwork/Pluto-iOS#1]
When a user creates a new account they are sent to the school search bar. When the user selects a result preview, two fingers are required to select the result preview.

**Comment by faisalmlalani** [comment]
This also happens on the main events page. I'm assuming it has something to do with a tap gesture recognizer I added to the image view on the create event view. I'll look into it.

**Comment by faisalmlalani** [comment]
There was a tap gesture recognizer on the entire view that allowed the user to dismiss the keyboard, but it isn't needed. Removing it fixed the issue.
