### ISSUE TITLE
Visual Artifact on Profile Page When Another User Selects an Event

### ISSUE THREAD

**Issue by JMichaelScott** [PlutoNetwork/Pluto-iOS#2]
When the user is on their Profile page, if another user selects an event from either the events page or their profile page a visual artifact will appear on other users phones. This appears to be related to firebase access, or possibly how the app updates the user's profile view.

**Comment by faisalmlalani** [comment]
This was fixed by grabbing the data from Firebase using observeSingleEvent() instead of observe().
